build: bump nx-aarch64 toolchain

diff --git a/Taskfile.yml b/Taskfile.yml
--- a/Taskfile.yml
+++ b/Taskfile.yml
@@ -5,7 +5,7 @@ version: '3'
 vars:
   # Sources to check with clang-format/clang-tidy
   SOURCES: lib include/nn include/nnc
-  NX_AARCH64: 22.1.8-1
+  NX_AARCH64: 22.1.8-3
 
 env:
   NX_AARCH64: '{{.NX_AARCH64}}'
@@ -98,18 +98,33 @@ tasks:
   clang-format:
     cmds:
       - silent: true
-        cmd: > 
+        cmd: | 
+          clang=$NX_CLANG
+          if [ ! -d "$clang" ]; then
+            clang="toolchain/nx-aarch64-$NX_AARCH64"
+          fi
+          if [ ! -d "$clang" ]; then
+            echo "cannot find nx-aarch64 - please run 'task configure'"
+            exit 1
+          fi
+          clang_format="$clang/bin/clang-format"
           echo 'running clang-format with {{numCPU}} cpus with args: {{.ARGS}}';
-          find {{.SOURCES}}
-          -regextype posix-extended
-          -regex '.*\.[ch](\+\+|pp|xx|c|h)?'
-          | xargs -P {{numCPU}} -n 1 clang-format {{.ARGS}}
+          find {{.SOURCES}} -regextype posix-extended -regex '.*\.[ch](\+\+|pp|xx|c|h)?' | xargs -P {{numCPU}} -n 1 $clang_format {{.ARGS}}
   clang-tidy:
     vars:
-      CMD: clang-tidy --warnings-as-errors="*" --header-filter="include/(nn|nvn|nvnTool|nv)" -p build --quiet
+      ARGS: --warnings-as-errors="*" --header-filter="include/(nn|nvn|nvnTool|nv)" -p build --quiet
     cmds:
       - silent: true
         cmd: |
+          clang=$NX_CLANG
+          if [ ! -d "$clang" ]; then
+            clang="toolchain/nx-aarch64-$NX_AARCH64"
+          fi
+          if [ ! -d "$clang" ]; then
+            echo "cannot find nx-aarch64 - please run 'task configure'"
+            exit 1
+          fi
+          clang_tidy="$clang/bin/clang-tidy"
           echo 'running clang-tidy with {{numCPU}} cpus';
-          find {{.SOURCES}} -regextype posix-extended -regex '.*\.[ch](\+\+|pp|xx|c|h)?' | xargs -P {{numCPU}} -n 1 sh -c 'printf "\r\033[Kclang-tidy: $1"; {{.CMD}} "$1"' _;
+          find {{.SOURCES}} -regextype posix-extended -regex '.*\.[ch](\+\+|pp|xx|c|h)?' | xargs -P {{numCPU}} -n 1 sh -c 'printf "\r\033[Kclang-tidy: $1"; '$clang_tidy' {{.ARGS}} "$1"' _;
           echo ''
